name: Deploy

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@master
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@master
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push image
      uses: docker/build-push-action@master
      with:
        context: .
        push: true
        tags: |
          ghcr.io/Crosbic/redux-docker-example:latest
