name: Deploy

on:
  push:
    branches: 
      - master
      
  workflow_dispatch:

jobs:
  deploy:
  
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      id-token: write
      
    steps:
    
    - name: Checkout code
      uses: actions/checkout@master
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@master
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push image
      uses: docker/build-push-action@master
      with:
        context: .
        push: true
        tags: |
          ghcr.io/crosbic/redux-docker-example:latest

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
